export const JAVA_KEYWORD_DOCS = {
  import: {en: 'Bring a package or class into this file so its name can be used.', zh: '把一个包或类引入本文件，这样就能使用它的名字。'},
  package: {en: 'Declare which package this class belongs to.', zh: '声明这个类属于哪个包。'},
  class: {en: 'Define a new type. The body inside the braces is the class.', zh: '定义一个新类型。花括号里的代码就是类体。'},
  interface: {en: 'A type that lists methods a class must implement.', zh: '一种类型，列出实现类必须提供的方法。'},
  enum: {en: 'A fixed set of named constants.', zh: '一组固定的命名常量。'},
  public: {en: 'Visible to every other class.', zh: '对所有其他类可见。'},
  private: {en: 'Visible only inside this class.', zh: '只在这个类内部可见。'},
  protected: {en: 'Visible in this class, its package, and subclasses.', zh: '在本类、同包和子类中可见。'},
  static: {en: 'Belongs to the class, not to one instance. `main` is static so it can run without `new`.', zh: '属于类，而不是某个实例。`main` 是 static，所以不用 `new` 也能运行。'},
  final: {en: 'Cannot be reassigned, overridden, or subclassed, depending on where it is used.', zh: '不能再赋值、不能重写，或不能再被继承，取决于用在哪里。'},
  void: {en: 'The method returns no value.', zh: '这个方法不返回值。'},
  int: {en: 'A 32-bit integer type.', zh: '32 位整数类型。'},
  long: {en: 'A 64-bit integer type.', zh: '64 位整数类型。'},
  double: {en: 'A double-precision floating-point type.', zh: '双精度浮点类型。'},
  boolean: {en: 'A true or false value.', zh: '真或假。'},
  char: {en: 'A single character.', zh: '一个字符。'},
  String: {en: 'Text. Immutable; methods like `length()` return a new result or a view.', zh: '文本。不可变；`length()` 等方法返回结果或视图。'},
  new: {en: 'Create an object and run its constructor.', zh: '创建一个对象并运行它的构造方法。'},
  return: {en: 'Leave the method and hand a value back to the caller.', zh: '离开方法，并把一个值交还给调用者。'},
  if: {en: 'Run the following block only when the condition is true.', zh: '只有条件为真时才运行后面的代码块。'},
  else: {en: 'Block that runs when the matching if was false.', zh: '配对的 if 为假时运行这个块。'},
  for: {en: 'Repeat a block. Often walks an index or each item of a collection.', zh: '重复一个代码块。常用来走下标或集合中的每一项。'},
  while: {en: 'Repeat the block as long as the condition stays true.', zh: '只要条件保持为真就重复这个代码块。'},
  do: {en: 'A loop that runs the body once, then repeats while the condition is true.', zh: '先执行一次循环体，然后在条件为真时继续重复。'},
  switch: {en: 'Choose a branch by matching a value against case labels.', zh: '用值与各个 case 匹配，选择一个分支。'},
  case: {en: 'One label inside switch. The first matching case runs.', zh: 'switch 中的一个标签。第一个匹配的 case 会执行。'},
  break: {en: 'Leave the nearest loop or switch immediately.', zh: '立刻离开最近的循环或 switch。'},
  continue: {en: 'Skip the rest of this loop iteration and start the next one.', zh: '跳过这一轮循环剩下的代码，开始下一轮。'},
  try: {en: 'Run code that might throw, and pair it with catch or finally.', zh: '运行可能抛出异常的代码，并与 catch 或 finally 配对。'},
  catch: {en: 'Handle an exception thrown in the matching try.', zh: '处理配对 try 中抛出的异常。'},
  finally: {en: 'Run this block whether the try succeeded or threw.', zh: '无论 try 成功还是抛出异常，都会运行这个块。'},
  throw: {en: 'Raise an exception.', zh: '抛出一个异常。'},
  throws: {en: 'Declare that this method may throw the named checked exception.', zh: '声明这个方法可能抛出指定的受检异常。'},
  extends: {en: 'This class inherits from another class.', zh: '这个类继承另一个类。'},
  implements: {en: 'This class provides the methods of an interface.', zh: '这个类提供某个接口的方法。'},
  this: {en: 'The current instance. `this.x` is the field, not a parameter of the same name.', zh: '当前实例。`this.x` 是字段，不是同名参数。'},
  super: {en: 'The parent class. `super()` runs the parent constructor.', zh: '父类。`super()` 会运行父类构造方法。'},
  null: {en: 'No object. Calling a method on null throws NullPointerException.', zh: '空引用。对 null 调用方法会抛出 NullPointerException。'},
  true: {en: 'The boolean true value.', zh: '布尔真值。'},
  false: {en: 'The boolean false value.', zh: '布尔假值。'},
  main: {en: 'The method the JVM starts. Signature is `public static void main(String[] args)`.', zh: 'JVM 启动时调用的方法。签名是 `public static void main(String[] args)`。'},
  println: {en: 'Write a line to standard output and then a newline. `System.out.println(...)`.', zh: '把一行写到标准输出，并换行。`System.out.println(...)`。'},
  print: {en: 'Write text to standard output without adding a newline.', zh: '把文本写到标准输出，不加换行。'},
  length: {en: 'Number of characters in a String, or the size of an array.', zh: '字符串的字符数，或数组的长度。'},
  equals: {en: 'Value comparison. Use this for strings, not `==`.', zh: '按值比较。比较字符串要用它，不要用 `==`。'},
  size: {en: 'Number of elements in a list, set, or map.', zh: '列表、集合或映射中的元素个数。'},
  get: {en: 'Read the value at an index or key.', zh: '读取某个下标或键对应的值。'},
  add: {en: 'Insert an element into a list or set.', zh: '把一个元素加入列表或集合。'},
  put: {en: 'Store a key and value in a map.', zh: '在映射中存放一个键和值。'},
  remove: {en: 'Delete an element from a collection.', zh: '从集合中删除一个元素。'},
  contains: {en: 'True if the collection holds that value.', zh: '集合包含该值则为真。'},
  System: {en: 'The class that owns `out`, `err`, and `exit`.', zh: '拥有 `out`、`err` 和 `exit` 的类。'},
  out: {en: 'Standard output stream on `System`. `System.out` is where `println` writes.', zh: 'System 上的标准输出流。`println` 写到 `System.out`。'},
  util: {en: 'Package `java.util`. Everyday collections, `Scanner`, `Random`, and dates.', zh: '包 `java.util`。常用集合、`Scanner`、`Random` 和日期。'},
  Scanner: {en: 'From `java.util`. Reads tokens from input. `nextInt()` and `nextLine()` are the usual calls.', zh: '来自 `java.util`。从输入读取记号。常用 `nextInt()` 和 `nextLine()`。'},
  nextInt: {en: 'Scanner method. Read the next integer token.', zh: 'Scanner 的方法。读取下一个整数。'},
  nextLine: {en: 'Scanner method. Read the rest of the line, including spaces.', zh: 'Scanner 的方法。读入这一行剩下的内容，包括空格。'},
  Random: {en: 'From `java.util`. A random-number generator. `nextInt(n)` is in `0 .. n-1`.', zh: '来自 `java.util`。随机数发生器。`nextInt(n)` 得到 `0` 到 `n-1`。'},
  Math: {en: 'The `java.lang.Math` class. Static helpers: `abs`, `sqrt`, `pow`, `max`, `min`, `floor`, `ceil`.', zh: '`java.lang.Math` 类。静态工具：`abs`、`sqrt`、`pow`、`max`、`min`、`floor`、`ceil`。'},
  abs: {en: 'Math.abs(x). The absolute value, never negative.', zh: 'Math.abs(x)。绝对值，不会是负数。'},
  sqrt: {en: 'Math.sqrt(x). The square root, as a double.', zh: 'Math.sqrt(x)。平方根，结果是 double。'},
  pow: {en: 'Math.pow(a, b). a raised to the power b.', zh: 'Math.pow(a, b)。a 的 b 次方。'},
  max: {en: 'Math.max(a, b). The larger of two values.', zh: 'Math.max(a, b)。两个值中较大的那个。'},
  min: {en: 'Math.min(a, b). The smaller of two values.', zh: 'Math.min(a, b)。两个值中较小的那个。'},
  floor: {en: 'Math.floor(x). The greatest integer that is not greater than x.', zh: 'Math.floor(x)。不大于 x 的最大整数。'},
  ceil: {en: 'Math.ceil(x). The smallest integer that is not less than x.', zh: 'Math.ceil(x)。不小于 x 的最小整数。'},
  round: {en: 'Math.round(x). Round to the nearest integer.', zh: 'Math.round(x)。四舍五入到最近的整数。'},
  random: {en: 'Math.random(). A double in `[0.0, 1.0)`.', zh: 'Math.random()。`[0.0, 1.0)` 之间的一个 double。'},
  Integer: {en: 'The int wrapper. `Integer.parseInt(s)` turns text into an int.', zh: 'int 的包装类。`Integer.parseInt(s)` 把文本变成 int。'},
  Character: {en: 'The char wrapper. Helpers such as `toUpperCase` on one character.', zh: 'char 的包装类。例如对一个字符做 `toUpperCase`。'},
  StringBuilder: {en: 'A mutable text buffer. `append` adds pieces; `toString` finishes the string.', zh: '可变的文本缓冲。`append` 追加片段，`toString` 得到最终字符串。'},
  append: {en: 'Add text to a StringBuilder. Returns the same builder so calls can chain.', zh: '把文本加到 StringBuilder。返回同一个对象，所以可以连续调用。'},
  charAt: {en: 'The character at an index. `s.charAt(0)` is the first character.', zh: '某个下标上的字符。`s.charAt(0)` 是第一个字符。'},
  compareTo: {en: 'Order two strings. Negative, zero, or positive, like a dictionary compare.', zh: '比较两个字符串的顺序。返回负、零或正，像字典序比较。'},
  equalsIgnoreCase: {en: 'True if two strings match ignoring letter case.', zh: '忽略大小写时两个字符串相同则为真。'},
  toLowerCase: {en: 'A new string with letters in lowercase.', zh: '字母变成小写的新字符串。'},
  toUpperCase: {en: 'A new string with letters in uppercase.', zh: '字母变成大写的新字符串。'},
  toCharArray: {en: 'The string as a `char[]`.', zh: '把字符串变成 `char[]`。'},
  DecimalFormat: {en: 'From `java.text`. Format a number with a pattern such as `"0.00"`.', zh: '来自 `java.text`。用 `"0.00"` 这样的模式格式化数字。'},
  RoundingMode: {en: 'From `java.math`. How to round, such as `HALF_UP`.', zh: '来自 `java.math`。舍入方式，例如 `HALF_UP`。'},
  format: {en: 'Apply a pattern or format string to a value.', zh: '按模式或格式字符串格式化一个值。'},
  ArrayList: {en: 'A resizable list. `add`, `get`, `size`, `remove`. Import `java.util.ArrayList`.', zh: '可变长列表。`add`、`get`、`size`、`remove`。'},
  HashMap: {en: 'A hash map. `put(key, value)` stores, `get(key)` reads.', zh: '哈希表。`put(key, value)` 存放，`get(key)` 读取。'},
  HashSet: {en: 'A hash set of unique elements. `add` and `contains`.', zh: '元素不重复的哈希集合。`add` 和 `contains`。'},
  List: {en: 'An ordered collection. `ArrayList` is the usual implementation.', zh: '有序集合。常用实现是 `ArrayList`。'},
  Map: {en: 'A collection of keys to values. `HashMap` is the usual implementation.', zh: '键到值的集合。常用实现是 `HashMap`。'},
  Set: {en: 'A collection of unique elements. `HashSet` is the usual implementation.', zh: '元素不重复的集合。常用实现是 `HashSet`。'},
  Collections: {en: 'Utility class for lists and sets. `sort`, `reverse`, `frequency`.', zh: '列表和集合的工具类。`sort`、`reverse`、`frequency`。'},
  Arrays: {en: 'Utility class for arrays. `asList`, `sort`, `toString`.', zh: '数组的工具类。`asList`、`sort`、`toString`。'},
  asList: {en: 'Arrays.asList. Wrap values in a fixed-size list.', zh: '把几个值包成一个固定大小的列表。'},
  parseInt: {en: 'Integer.parseInt(s). Turn text into an int. Bad text throws NumberFormatException.', zh: '把文本变成 int。非法文本会抛出 NumberFormatException。'},
  valueOf: {en: 'Box a primitive, or parse text. `Integer.valueOf("3")` is an Integer.', zh: '装箱基本类型，或解析文本。`Integer.valueOf("3")` 得到 Integer。'},
  toString: {en: 'The text form of an object. StringBuilder uses it to finish the built string.', zh: '对象的文本形式。StringBuilder 用它得到拼好的字符串。'},
  substring: {en: 'A slice of a string. `s.substring(0, 3)` is the first three characters.', zh: '字符串的一段。`s.substring(0, 3)` 是前三个字符。'},
  indexOf: {en: 'The first index of a character or substring, or -1 if missing.', zh: '字符或子串第一次出现的下标，找不到则是 -1。'},
  startsWith: {en: 'True if the string begins with that prefix.', zh: '字符串以该前缀开头则为真。'},
  endsWith: {en: 'True if the string ends with that suffix.', zh: '字符串以该后缀结尾则为真。'},
  isEmpty: {en: 'True if a string, list, or map has no elements.', zh: '字符串、列表或映射没有元素时为真。'},
  keySet: {en: 'The set of keys in a map. Often used in `for (String k : map.keySet())`.', zh: '映射中所有键的集合。常用于 `for (String k : map.keySet())`。'},
  values: {en: 'The collection of values in a map.', zh: '映射中所有的值。'},
  entrySet: {en: 'The set of key-value pairs in a map.', zh: '映射中所有的键值对。'},
  getOrDefault: {en: 'Map lookup that returns a fallback when the key is missing.', zh: '映射查找。键不存在时返回备用值。'},
  containsKey: {en: 'True if the map has that key.', zh: '映射包含该键则为真。'},
  clear: {en: 'Remove every element from a list, set, or map.', zh: '清空列表、集合或映射。'},
  sort: {en: 'Collections.sort or Arrays.sort. Order the elements in place.', zh: '就地把元素排好序。'},
  reverse: {en: 'Collections.reverse. Reverse a list in place.', zh: '就地把列表反转。'},
  Optional: {en: 'A value that may be absent. `Optional.ofNullable` and `orElse`.', zh: '可能不存在的值。`Optional.ofNullable` 和 `orElse`。'},
  orElse: {en: 'The value inside an Optional, or this fallback if it is empty.', zh: 'Optional 里的值；若为空则用这个备用值。'},
  stream: {en: 'Start a pipeline over a collection. Then `filter`, `map`, `collect`.', zh: '在集合上开始一条流水线。然后 `filter`、`map`、`collect`。'},
  filter: {en: 'Keep elements that pass a test.', zh: '留下通过检测的元素。'},
  collect: {en: 'Finish a stream into a list, set, or other result.', zh: '把流收成列表、集合或其他结果。'},
  forEach: {en: 'Run a block once for each element.', zh: '对每个元素执行一次。'},
  Objects: {en: 'Null-safe helpers. `Objects.equals(a, b)` is safe when either side is null.', zh: '空安全的工具。任一边是 null 时 `Objects.equals(a, b)` 也安全。'},
  lang: {en: 'Package `java.lang`. Automatically imported: `String`, `Math`, `Integer`, `System`.', zh: '包 `java.lang`。自动导入：`String`、`Math`、`Integer`、`System`。'},
  text: {en: 'Package `java.text`. Formatting helpers such as `DecimalFormat`.', zh: '包 `java.text`。格式化工具，例如 `DecimalFormat`。'},
  math: {en: 'Package `java.math`. `BigInteger`, `BigDecimal`, and `RoundingMode`.', zh: '包 `java.math`。`BigInteger`、`BigDecimal` 和 `RoundingMode`。'},
  BigDecimal: {en: 'An exact decimal. Use it for money. `setScale` controls the rounding.', zh: '精确小数。适合金额。`setScale` 控制舍入。'},
  BigInteger: {en: 'An integer with no fixed bit width.', zh: '没有固定位宽的整数。'},
  setScale: {en: 'Change how many digits a BigDecimal keeps after the decimal point.', zh: '改变 BigDecimal 小数点后保留的位数。'},
  next: {en: 'Scanner method. Read the next token, stopping at whitespace.', zh: 'Scanner 的方法。读取下一个记号，遇到空白就停。'},
  in: {en: 'Standard input on `System`. `new Scanner(System.in)` reads the keyboard.', zh: 'System 上的标准输入。`new Scanner(System.in)` 从键盘读取。'},
  LinkedList: {en: 'A list implemented as a linked list. Also a `Queue`: `add`, `peek`, `poll`.', zh: '用链表实现的列表。也可以当队列用：`add`、`peek`、`poll`。'},
  Queue: {en: 'A FIFO collection. `offer` or `add` at the back, `peek` to look, `poll` to remove.', zh: '先进先出的集合。`offer` 或 `add` 加到队尾，`peek` 查看，`poll` 取出。'},
  ArrayDeque: {en: 'A resizable double-ended queue. Prefer this to `Stack` for a stack or queue.', zh: '可变长的双端队列。当栈或队列用时，优先用它而不是 `Stack`。'},
  PriorityQueue: {en: 'A heap. `peek` is the smallest element unless you pass a different comparator.', zh: '堆。除非传入别的比较器，否则 `peek` 是最小的元素。'},
  TreeMap: {en: 'A map kept in key order.', zh: '按键排序的映射。'},
  TreeSet: {en: 'A set kept in element order. `first` and `last` are the ends.', zh: '按元素排序的集合。`first` 和 `last` 是两端。'},
  first: {en: 'The smallest element in a sorted set, or the first item of a list.', zh: '有序集合里最小的元素，或列表的第一项。'},
  last: {en: 'The largest element in a sorted set, or the last item of a list.', zh: '有序集合里最大的元素，或列表的最后一项。'},
  HALF_UP: {en: 'Round away from zero when the discarded digit is 5 or more.', zh: '被舍弃的数字大于等于 5 时向远离 0 的方向舍入。'},
  peek: {en: 'Look at the next queue or deque element without removing it.', zh: '查看队列或双端队列的下一个元素，但不删除。'},
  poll: {en: 'Remove and return the next queue element, or null if empty.', zh: '取出队列的下一个元素。队列为空则返回 null。'},
  offer: {en: 'Add an element to a queue. Returns false if the queue refuses it.', zh: '向队列加入一个元素。若队列拒绝则返回 false。'},
  frequency: {en: 'Collections.frequency. How many times a value appears in a collection.', zh: '某个值在集合里出现了几次。'},
  shuffle: {en: 'Collections.shuffle. Put a list into a random order.', zh: '把列表打乱成随机顺序。'},
  binarySearch: {en: 'Find an index in a sorted array or list. Negative if the value is missing.', zh: '在已排序的数组或列表里查找下标。找不到则是负数。'},
  fill: {en: 'Arrays.fill. Set every slot of an array to the same value.', zh: '把数组的每个位置都设成同一个值。'},
  copyOf: {en: 'Arrays.copyOf. A new array copied from another, with a chosen length.', zh: '从原数组复制出一个指定长度的新数组。'},
  replace: {en: 'A new string with a character or substring swapped for another.', zh: '把字符或子串换成另一个，得到新字符串。'},
  trim: {en: 'A new string with leading and trailing whitespace removed.', zh: '去掉首尾空白后的新字符串。'},
  split: {en: 'Break a string into a `String[]` on a regex.', zh: '按正则把字符串拆成 `String[]`。'},
  of: {en: 'Build a value. `Optional.of` requires a non-null value. `List.of` makes an immutable list.', zh: '构造一个值。`Optional.of` 要求非 null。`List.of` 得到不可变列表。'},
  ofNullable: {en: 'An Optional that is empty when the argument is null.', zh: '参数是 null 时得到空的 Optional。'},
  isPresent: {en: 'True if an Optional holds a value.', zh: 'Optional 里有值时为真。'},
  Exception: {en: 'The usual base type for things `catch` can handle.', zh: '通常能被 `catch` 处理的异常基类。'},
  var: {en: 'Let the compiler infer a local variable’s type from the initializer.', zh: '让编译器根据初始值推断局部变量的类型。'},
  instanceof: {en: 'True if the object is an instance of that type.', zh: '对象是该类型的实例时为真。'},
  abstract: {en: 'A class or method that is incomplete until a subclass fills it in.', zh: '需要子类补全的类或方法。'},
  Iterator: {en: 'Walk a collection with `hasNext` and `next`.', zh: '用 `hasNext` 和 `next` 遍历集合。'},
  hasNext: {en: 'True if an Iterator or Scanner still has another element.', zh: '迭代器或 Scanner 还有下一个元素时为真。'},
  Entry: {en: 'One key-value pair from a map. `Map.Entry`.', zh: '映射里的一个键值对。`Map.Entry`。'},
  getKey: {en: 'The key of a map entry.', zh: '映射条目的键。'},
  getValue: {en: 'The value of a map entry.', zh: '映射条目的值。'},
  io: {en: 'Package `java.io`. Streams and readers, such as `BufferedReader`.', zh: '包 `java.io`。流和读取器，例如 `BufferedReader`。'},
  BufferedReader: {en: 'From `java.io`. Read text a line at a time with `readLine`.', zh: '来自 `java.io`。按行读取文本，用 `readLine`。'},
  readLine: {en: 'Read one line, or null at the end of input.', zh: '读入一行。输入结束时返回 null。'},
  close: {en: 'Release a scanner, reader, or other resource.', zh: '释放 scanner、读取器或其他资源。'},
};

function docText(entry, lang) {
  if (!entry) return '';
  if (typeof entry === 'string') return entry;
  if (lang === 'zh') return entry.zh || entry.en || '';
  return entry.en || entry.zh || '';
}

export function docsForLine(line, lang = 'en') {
  const text = String(line || '');
  const hits = [];
  const seen = new Set();
  const imported = [...text.matchAll(/\bimport\s+(?:static\s+)?([\w.]+)/g)].map((m) => m[1].split('.').pop());
  const tokens = [...imported, ...(text.match(/[A-Za-z_][A-Za-z0-9_]*/g) || [])];
  for (const token of tokens) {
    if (seen.has(token) || !JAVA_KEYWORD_DOCS[token]) continue;
    seen.add(token);
    hits.push({token, doc: docText(JAVA_KEYWORD_DOCS[token], lang)});
  }
  return hits;
}
